python image_1bpp_converter.py sangria_logo1.png
python image_1bpp_converter.py sangria_logo2.png
python font_converter.py ../font/font.png
python image_1bpp_converter.py ../font/dc_plug.png
python image_1bpp_converter.py ../font/empty.png
python image_1bpp_converter.py ../font/half.png
python image_1bpp_converter.py ../font/high.png
python image_1bpp_converter.py ../font/full.png
python image_1bpp_converter.py ../font/no_battery.png
python image_1bpp_converter.py ../font/shift.png
python image_1bpp_converter.py ../font/alt.png
python image_1bpp_converter.py ../font/sym.png
python image_1bpp_converter.py ../font/ctrl.png
python image_1bpp_converter.py ../font/ac_adapter.png
python image_1bpp_converter.py ../font/usb_power.png
python image_1bpp_converter.py ../font/big_ac_power.png
python image_1bpp_converter.py ../font/big_usb_power.png
python image_1bpp_converter.py ../font/big_no_power.png
python image_1bpp_converter.py ../font/big_otg_power.png
pause
