python image_1bpp_converter.py sangria_logo1.png
python image_1bpp_converter.py sangria_logo2.png
python font_converter.py ../font/font.png
python image_1bpp_converter.py ../font/dc_plug.png
python image_1bpp_converter.py ../font/empty.png
python image_1bpp_converter.py ../font/half.png
python image_1bpp_converter.py ../font/high.png
python image_1bpp_converter.py ../font/full.png
python image_1bpp_converter.py ../font/no_battery.png
python image_1bpp_converter.py ../font/shift.png
python image_1bpp_converter.py ../font/alt.png
python image_1bpp_converter.py ../font/sym.png
python image_1bpp_converter.py ../font/ctrl.png
python image_1bpp_converter.py ../font/ac_adapter.png
python image_1bpp_converter.py ../font/usb_power.png
python image_1bpp_converter.py ../font/big_ac_power.png
python image_1bpp_converter.py ../font/big_usb_power.png
python image_1bpp_converter.py ../font/big_no_power.png
python image_1bpp_converter.py ../font/big_otg_power.png
python image_1bpp_converter.py ../font/big_bq_is_not_detect.png
python image_1bpp_converter.py ../font/big_battery_empty_a.png
python image_1bpp_converter.py ../font/big_battery_empty_b.png
python image_1bpp_converter.py ../font/big_battery_low_a.png
python image_1bpp_converter.py ../font/big_battery_low_b.png
python image_1bpp_converter.py ../font/big_battery_high_a.png
python image_1bpp_converter.py ../font/big_battery_high_b.png
python image_1bpp_converter.py ../font/big_battery_full.png
python image_1bpp_converter.py ../font/battery_000.png
python image_1bpp_converter.py ../font/battery_020.png
python image_1bpp_converter.py ../font/battery_040.png
python image_1bpp_converter.py ../font/battery_060.png
python image_1bpp_converter.py ../font/battery_080.png
python image_1bpp_converter.py ../font/battery_100.png
python image_1bpp_converter.py ../font/charge0.png
python image_1bpp_converter.py ../font/charge1.png
python image_1bpp_converter.py ../font/charge2.png
python image_1bpp_converter.py ../font/charge3.png
python image_1bpp_converter.py ../font/charge4.png
python image_1bpp_converter.py ../font/charge5.png
python image_1bpp_converter.py ../font/charge6.png
python image_1bpp_converter.py ../font/charge7.png
python image_1bpp_converter.py ../font/no_charge.png
python image_1bpp_converter.py ../font/pre_charge0.png
python image_1bpp_converter.py ../font/pre_charge1.png
python image_1bpp_converter.py ../font/charge_termination_done.png
pause
